---
title: DevNexus 2018
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  tracks:
    title: Tracks
    output: false
  organizers:
    output: true
    permalink: /:collection/:path
email: info@ajug.org
description: SouthEast's largest developer conference.
baseurl:
url:
markdown: kramdown
theme:
plugins:
- jekyll-feed
