---
title: DevNexus 2019
timezone: UTC
collections:
  speakers:
    title: Speakers 2019
    output: true
    permalink: /:collection/:path
  events:
     title: Presentations 2019
     output: true
     permalink: /presentations/:path/
  event-instructions:
     title: Workshop Prep 2019
     output: true
     permalink: /presentations/:path/instructions
  sponsors:
    title: Sponsors
    output: true
  tracks:
    title: Tracks
    output: false
  organizers:
    title: Organizers
    output: true
    permalink: /:collection/:path
email: info@ajug.org
description: SouthEast's largest developer conference.
baseurl:
url:
links:
   cfp: https://cfp.devnexus.com/en/dn2019/cfp/session/new
   register: https://devnexus2019.ajug.org/s/register.html
markdown: kramdown
theme:
_editor:
  default_path: /about/
defaults:
  -
   scope:
     path: "archive"
     type: "pages"
   values:
     layout: "archive"
  -
   scope:
     path: ""
     type: "event-instructions"
   values:
     layout: "workshop_instructions"

_options:
  logo_image:
    width: 360
    height: 360
    resize_style: "cover"
    mime_type: "image/png"
    expandable: false
