---
safe: true
exclude: ['_presite_plugins', 'README.md', '_move_to_arhcive.html']
title: Devnexus 2024
timezone: UTC
active-header: navigation-post-show.html
cfp-is-open: true
registration: closed
feedback: NOTshow
collections:
  speakers:
    title: Speakers 2024
    output: true
    permalink: /:collection/:slug
  events:
     title: Presentations 2024
     output: true
     permalink: /presentations/:slug/
  event-instructions:
     title: Workshop Prep 2024
     output: true
     permalink: /presentations/:path/instructions
  tracks:
    title: Tracks
    output: false
  organizers:
    title: Organizers
    output: true
    permalink: /:collection/:path
email: info@ajug.org
description: Largest Java Conference in the USA.
baseurl:
url:
uploads_dir: "/uploads"
links:
   stay-informed:
   hotel-block:
   cfp: https://sessionize.com/devnexus-2024/
   register: https://reg.connectevents.io/ConnectEvents/devnexus
   signIn: https://reg.connectevents./ConnectEvents/devnexus
   announcements: https://twitter.com/devnexus
   recordings: https://www.recallact.com/ajug
   reg_maillist: https://ajug.us7.list-manage.com/subscribe/post?u=0b3b17489713c9e7c62595dd3&amp;id=51e5b6d965
twitter_card:
  default_image: https://devnexus.com/assets/img/twittercard.png
  type: summary
  site: "@devnexus"
  creator:  "@atlantajug"
markdown: kramdown
theme:
plugins:
  - jekyll-seo-tag
_editor:
  default_path: /about/
defaults:
  - scope:
      path: "archive"
    values:
      layout: "archive"
  - scope:
     path: ""
     type: "event-instructions"
    values:
     layout: "workshop_instructions"
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/img/sponsors"
    values: 
      sponsor: true
  - scope:
       path: ""
       type: "events"
    values:
      layout: "preso_details" 
  - scope:
       path: ""
       type: "speakers"
    values:
      layout: "speaker_bio"        
_options:
  logo_image:
    width: 300
    height: 300
    resize_style: "cover"
    expandable: false
    uploads_dir: /assets/img/sponsors/
_defaults:
  logo_image: "/assets/img/sponsor.png"
