---
title: DevNexus 2018
timezone: UTC
collections:
  speakers:
    title: Speakers 2018
    output: true
    permalink: /:collection/:path
  events:
     title: Presentations 2018
     output: true
     permalink: /presentations/:path
  sponsors:
    title: Sponsors
    output: true
  tracks:
    title: Tracks
    output: false
  organizers:
    title: Organizers
    output: true
    permalink: /:collection/:path
email: info@ajug.org
description: SouthEast's largest developer conference.
baseurl:
url:
links:
   cfp: https://cfp.devnexus.com/en/dn2018/cfp/session/new
   register: https://devnexus2018.ajug.org/s/register.html
markdown: kramdown
theme:
_editor:
  default_path: /about/
defaults:
  -
   scope:
     path: "archive"
     type: "pages"
   values:
     layout: "archive"
_options:
  logo_image:
    width: 360
    height: 360
    resize_style: "cover"
    mime_type: "image/png"
    expandable: false
