---
title: DevNexus 2018
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@ajug.org
description: 'SouthEast''s largest developer conference.

'
baseurl: 
url: 
markdown: kramdown
theme: jekyll-theme-devnexus 
plugins:
- jekyll-feed
