---
safe: true
exclude: ['_presite_plugins', 'README.md']
title: Devnexus 2021
timezone: UTC
active-header: navigation-post-show.html
registration: closed
collections:
  speakers:
    title: Speakers 2021
    output: true
    permalink: /:collection/:path
  events:
     title: Presentations 2021
     output: true
     permalink: /presentations/:path/
  event-instructions:
     title: Workshop Prep 2021
     output: true
     permalink: /presentations/:path/instructions
  tracks:
    title: Tracks
    output: false
  organizers:
    title: Organizers
    output: true
    permalink: /:collection/:path
email: info@ajug.org
description: Largest Java Conference in the USA.
baseurl:
url:
uploads_dir: "/uploads"
links:
   cfp: https://cfp.devnexus.com/en/dn2020/cfp/session/new
   register: https://reg.connectevents.io/ConnectEvents/devnexus2020/
   announcements: https://twitter.com/devnexus
   recordings: https://www.recallact.com/ajug
markdown: kramdown
theme:
_editor:
  default_path: /about/
defaults:
  - scope:
      path: "archive"
    values:
      layout: "archive"
  - scope:
     path: ""
     type: "event-instructions"
    values:
     layout: "workshop_instructions"
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/img/sponsors"
    values:
      sponsor: true
_options:
  logo_image:
    width: 360
    height: 360
    resize_style: "cover"
    expandable: false
    uploads_dir: /assets/img/sponsors/
_defaults:
  logo_image: "/assets/img/sponsor.png"
