server:
  port: 8090
  servlet-path: /
  session-timeout: 20
  tomcat:
    compression: on
    compressable-mime-types: application/json,application/xml,text/html,text/xml,text/plain
multipart:
  enabled: true
  max-file-size: 5Mb
  max-request-size: 10Mb
devnexus:
  twitter:
    enabled: false
    oauth:
      consumerKey:
      consumerSecret:
      accessToken:
      accessTokenSecret:
  mail:
    enabled: false
    authenticationEnabled: false
    debugEnabled: false
    user:
      id:
      password:
      from: info@ajug.org
      cc:
    smtp:
      port: 25
      host: localhost
  recaptcha:
    enabled: false
    publicKey:
    privateKey:
spring:
  datasource:
    url: jdbc:h2:mem:devnexus_demo
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
database:
  hibernate:
    dialect: com.devnexus.ting.core.hibernate.ImprovedH2Dialect
    show_sql: false
    generate_ddl: validate

TING_CLIENT_ID: fillme
TING_CLIENT_SECRET: fillme
TING_PUSH_URL: fillme
TING_PUSH_APP_ID: fillme
TING_PUSH_MASTER_SECRET: fillme

https:
    enabled: false

#paypal
PAYPAL_ACCOUNT: payments-facilitator@ajug.org
PAYPAL_ENDPOINT: api.sandbox.paypal.com
PAYPAL_CLIENT_ID: xxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxx_xxxxxxxxxx
PAYPAL_CLIENT_SECRET: xxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxx_xxxxxxxxxx